import { Screen } from './types';

export const SCREENS_DATA: Screen[] = [
  {
    id: 1,
    name: 'Kano Trade Fair Complex Entrance',
    location: 'Zoo Road, Kano',
    pricePerDay: 25000,
    footTraffic: 'High',
    impressionsPerDay: 15000,
    operatingHours: '8 AM - 10 PM',
    islamicSafe: true,
    imageUrl: 'https://picsum.photos/seed/kano1/600/400',
    lat: 11.975,
    lng: 8.541,
    businessType: 'Complex',
  },
  {
    id: 2,
    name: 'Ado Bayero Mall Atrium',
    location: 'Zoo Road, Kano',
    pricePerDay: 45000,
    footTraffic: 'High',
    impressionsPerDay: 25000,
    operatingHours: '10 AM - 9 PM',
    islamicSafe: true,
    imageUrl: 'https://picsum.photos/seed/kano2/600/400',
    lat: 11.978,
    lng: 8.545,
    businessType: 'Mall',
  },
  {
    id: 3,
    name: 'Farm Centre Phone Market',
    location: 'Farm Centre, Kano',
    pricePerDay: 20000,
    footTraffic: 'Medium',
    impressionsPerDay: 12000,
    operatingHours: '9 AM - 7 PM',
    islamicSafe: true,
    imageUrl: 'https://picsum.photos/seed/kano3/600/400',
    lat: 12.001,
    lng: 8.520,
    businessType: 'Market',
  },
  {
    id: 4,
    name: 'Kantin Kwari Market Hub',
    location: 'Kantin Kwari, Kano',
    pricePerDay: 30000,
    footTraffic: 'High',
    impressionsPerDay: 18000,
    operatingHours: '7 AM - 6 PM',
    islamicSafe: true,
    imageUrl: 'https://picsum.photos/seed/kano4/600/400',
    lat: 11.995,
    lng: 8.523,
    businessType: 'Market',
  },
  {
    id: 5,
    name: 'Sa\'adatu Rimi College of Education',
    location: 'Kumbotso, Kano',
    pricePerDay: 15000,
    footTraffic: 'Medium',
    impressionsPerDay: 8000,
    operatingHours: '8 AM - 5 PM',
    islamicSafe: true,
    imageUrl: 'https://picsum.photos/seed/kano5/600/400',
    lat: 11.971,
    lng: 8.502,
    businessType: 'University',
  },
  {
    id: 6,
    name: 'Bayero University Kano (BUK) New Site',
    location: 'Gwarzo Road, Kano',
    pricePerDay: 18000,
    footTraffic: 'High',
    impressionsPerDay: 10000,
    operatingHours: '24 Hours',
    islamicSafe: true,
    imageUrl: 'https://picsum.photos/seed/kano6/600/400',
    lat: 11.983,
    lng: 8.465,
    businessType: 'University',
  },
];